# Generated by Django 5.2.4 on 2025-07-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiatour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='Origin',
            new_name='origin',
        ),
    ]
